### ISSUE TITLE
rdb recovery failed

### ISSUE THREAD

**Issue by zhangliang-zl** [RedisGraph/RedisGraph#2898] opened 2023-02-17 10:53 UTC
redisgraph.so  2.8.6 
redis ：6.0.16

=== REDIS BUG REPORT START: Cut & paste starting from here ===
169086:M 17 Feb 2023 18:49:43.832 # ------------------------------------------------
169086:M 17 Feb 2023 18:49:43.833 # !!! Software Failure. Press left mouse button to continue
169086:M 17 Feb 2023 18:49:43.833 # Guru Meditation: Error loading data from RDB (short read or EOF). Read performed by module 'graph' about type 'graphmeta' after reading '0' bytes of a value for key named: '{asset}asset_70efc92a-af15-42e3-ab69-276250303246'. #module.c:3798
169086:M 17 Feb 2023 18:49:43.833 # (forcing SIGSEGV in order to print the stack trace)
169086:M 17 Feb 2023 18:49:43.833 # ------------------------------------------------
169086:M 17 Feb 2023 18:49:43.833 # Redis 6.0.16 crashed by signal: 11, si_code: 1
169086:M 17 Feb 2023 18:49:43.833 # Crashed running the instruction at: 0x4782a3
169086:M 17 Feb 2023 18:49:43.833 # Accessing address: 0xffffffffffffffff
169086:M 17 Feb 2023 18:49:43.833 # Failed assertion: <no assertion failed> (<no file>:0)

------ STACK TRACE ------
EIP:
/data/s/services/redisgraph/16479/server/bin/redis-server *:16479(_serverPanic+0x113)[0x4782a3]

Backtrace:
/data/s/services/redisgraph/16479/server/bin/redis-server *:16479(logStackTrace+0x2e)[0x47a5ee]
/data/s/services/redisgraph/16479/server/bin/redis-server *:16479(sigsegvHandler+0xa9)[0x47acb9]
/lib64/libpthread.so.0(+0xf5d0)[0x7fcd24b015d0]
/data/s/services/redisgraph/16479/server/bin/redis-server *:16479(_serverPanic+0x113)[0x4782a3]
/data/s/services/redisgraph/16479/server/bin/redis-server *:16479(moduleRDBLoadError+0x4a)[0x4aacfa]
/data/s/services/redisgraph/16479/server/bin/redis-server *:16479[0x4aad55]
/data/s/services/redisgraph/16479/server/so/redisgraph.so(RdbLoadNodes_v9+0x93)[0x7fcd1c7e3ae3]
/data/s/services/redisgraph/16479/server/so/redisgraph.so(RdbLoadGraph_v9+0x2cb)[0x7fcd1c7e3feb]
/data/s/services/redisgraph/16479/server/so/redisgraph.so(+0x1edca5)[0x7fcd1c7e1ca5]
/data/s/services/redisgraph/16479/server/bin/redis-server *:16479[0x45b350]
/data/s/services/redisgraph/16479/server/bin/redis-server *:16479(rdbLoadRio+0x248)[0x45d0e8]
/data/s/services/redisgraph/16479/server/bin/redis-server *:16479(rdbLoad+0x4d)[0x45daad]
/data/s/services/redisgraph/16479/server/bin/redis-server *:16479(loadDataFromDisk+0x8c)[0x43b5cc]
/data/s/services/redisgraph/16479/server/bin/redis-server *:16479(main+0x470)[0x42d020]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7fcd247473d5]
/data/s/services/redisgraph/16479/server/bin/redis-server *:16479[0x42d359]

**Comment by LiorKogan** [comment] 2023-02-17 11:11
Duplicate of #2811.

**Closed** 2023-02-17 11:12 UTC
