### ISSUE TITLE
Request that crashes Redis

### ISSUE THREAD

**Issue by Rambatino** [RedisGraph/RedisGraph#1617] opened 2021-03-08 12:39 UTC
Hello 👋 . We've been using the redis graph module internally and so far it's been absolutely amazing! 

Just recently, I've encountered an issue, most likely something to do with a recursive conditional traversal, that I'm guessing creates memory issues? The problem I never see a log in docker. The culprit is:

``` js
MATCH (m:Measure)-[:EQUALS*0..]-(:Measure)-[d:CAPTURES]-(:Measurement)-[:EQUALS*0..]-(me)-[l:CAPTURES]-(:Measure),
(s0:Scope)-[:SCOPED]-(me), 
(s1:Scope)-[:SCOPED]-(me), 
(s2:Scope)-[:SCOPED]-(me), 
(s3:Scope)-[:SCOPED]-(me), 
(:Measure)-[dd:CAPTURES]-(me)-[f:MEASURES]-(c:Constant) 

WHERE m.value = "ger" 
              AND s0.storage_key IN ["scope|sc7440455|s5e237e06|saff864d3"] 
              AND s1.storage_key IN ["scope|sad5f9bfc|sbf396750|i102"] 
              AND s2.storage_key IN ["scope|sad5f9bfc|s77153098|se8af8ab2"] 
              AND s3.storage_key IN ["scope|s31098462|s77153098|s5b76a3dd"] 

RETURN DISTINCT dd.storage_key, f.dimension, c.value, d.storage_key, m, f, c
``` 
It will even crash if there is no data in the graph and thus is purely due to the constructing of the query.

It does work, however, if I remove s3 scope and the AND clause that contains s3. 

Also, there may be a better way of writing such a query, but the difficulty I have is that I need to match on a measurement node that has a set of scopes connected to it, that contain these storage keys. I can't do a single WHERE because the scopes need to include all 4 of those storage keys, so a single WHERE doesn't cut it. 

Is there a better way of constructing this query? 

Either way it does crash redis, so it may be a bug on your end somewhere, too.

Using `redislabs/redisgraph:edge`

**Comment by jeffreylovitz** [comment] 2021-03-08 17:49
Hi @Rambatino,

You can specify a property value multiple times in a WHERE clause, so if I understand correctly your query could function as:
```
MATCH (m:Measure)-[:EQUALS*0..]-(:Measure)-[d:CAPTURES]-(:Measurement)-[:EQUALS*0..]-(me)-[l:CAPTURES]-(:Measure),
(s:Scope)-[:SCOPED]-(me), 
(:Measure)-[dd:CAPTURES]-(me)-[f:MEASURES]-(c:Constant) 

WHERE m.value = "ger" 
              AND s.storage_key IN ["scope|sc7440455|s5e237e06|saff864d3"] 
              AND s.storage_key IN ["scope|sad5f9bfc|sbf396750|i102"] 
              AND s.storage_key IN ["scope|sad5f9bfc|s77153098|se8af8ab2"] 
              AND s.storage_key IN ["scope|s31098462|s77153098|s5b76a3dd"] 

RETURN DISTINCT dd.storage_key, f.dimension, c.value, d.storage_key, m, f, c
```

Your provided query doesn't crash for me locally when run against an empty graph, but it does take an inordinate amount of time and memory, so I believe this is an OOM error. The problem lies in the logic that decides what is the best starting point for the traversal chain. This is an issue that we began addressing in #1325, I will make sure it is on our roadmap to revisit!

**Comment by Rambatino** [comment] 2021-03-08 18:44
Hi @jeffreylovitz, I just ran that query and it doesn't work. I don't think. 

Let's say you have a Measurement node, with multiple Scope nodes SCOPED to it. 


``` js
MERGE (m:Measure {value:"ger"})
MERGE (measurement:Measurement {storage_key:"ms14588b45|cdsc7470a42|s558de0a9"})
MERGE (clientnameRipple:Scope {storage_key:"scope|sc7440455|s5e237e06|saff864d3",value:"Ripple"})
MERGE (clientnameRipple)-[:SCOPED]-(m)
MERGE (clientnameRipple)-[:SCOPED]-(measurement)
MERGE (surveyid102:Scope {storage_key:"scope|sad5f9bfc|sbf396750|i102",value:102})
MERGE (surveyid102)-[:SCOPED]-(m)
MERGE (surveyid102)-[:SCOPED]-(measurement)
MERGE (surveycodexrp:Scope {storage_key:"scope|sad5f9bfc|s77153098|se8af8ab2",value:"xrp"})
MERGE (surveycodexrp)-[:SCOPED]-(m)
MERGE (surveycodexrp)-[:SCOPED]-(measurement)
MERGE (langcodeenGB:Scope {storage_key:"scope|s31098462|s77153098|s5b76a3dd",value:"en-GB"})
MERGE (langcodeenGB)-[:SCOPED]-(m)
MERGE (langcodeenGB)-[:SCOPED]-(measurement)
MERGE (clientnameRipple)-[:LINKS {key:"survey",dimension:"id"}]-(surveyid102)
MERGE (clientnameRipple)-[:LINKS {key:"survey",dimension:"code"}]-(surveycodexrp)
MERGE (clientnameRipple)-[:LINKS {key:"lang",dimension:"code"}]-(langcodeenGB)
MERGE (surveyid102)-[:LINKS {key:"client",dimension:"name"}]-(clientnameRipple)
MERGE (surveyid102)-[:LINKS {key:"survey",dimension:"code"}]-(surveycodexrp)
MERGE (surveyid102)-[:LINKS {key:"lang",dimension:"code"}]-(langcodeenGB)
MERGE (surveycodexrp)-[:LINKS {key:"client",dimension:"name"}]-(clientnameRipple)
MERGE (surveycodexrp)-[:LINKS {key:"survey",dimension:"id"}]-(surveyid102)
MERGE (surveycodexrp)-[:LINKS {key:"lang",dimension:"code"}]-(langcodeenGB)
MERGE (langcodeenGB)-[:LINKS {key:"client",dimension:"name"}]-(clientnameRipple)
MERGE (langcodeenGB)-[:LINKS {key:"survey",dimension:"id"}]-(surveyid102)
MERGE (langcodeenGB)-[:LINKS {key:"survey",dimension:"code"}]-(surveycodexrp)
MERGE (cbngh3:Constant {value:"male"})
MERGE (measurement)-[:MEASURES {dimension: 'gender'}]->(cbngh3)
MERGE (clientnameRipple)-[:SCOPED]-(cbngh3)
MERGE (surveyid102)-[:SCOPED]-(cbngh3)
MERGE (surveycodexrp)-[:SCOPED]-(cbngh3)
MERGE (langcodeenGB)-[:SCOPED]-(cbngh3)
MERGE (m)-[l:CAPTURES {storage_key: 'response_id|ms14588b45|cdsc7470a42|s558de0a9'}]->(measurement)RETURN l.storage_key
```

Resulting graph:

![image](https://user-images.githubusercontent.com/3631109/110366457-36c2dd00-803e-11eb-9409-9c58fc0b5e26.png)

A single scope can't be both "scope|sc7440455|s5e237e06|saff864d3" AND "scope|sad5f9bfc|sbf396750|i102" simultaneously which is why I don't think it works. Or am i misinterpreting the cypher query?

**Comment by jeffreylovitz** [comment] 2021-03-08 19:24
Oh, I see what you mean! (And sorry, my recommendation didn't make sense.)

I get the idea of your data from your given queries, but to verify, these are just for example purposes? They are missing elements like using multiple MATCH/MERGE clauses to bind variables like `clientnameRipple`, as well as having issues like undirected MERGE paths.

To make your initial query perform better, we really want to avoid repeating the `(s0:Scope)-[:SCOPED]-(me)` pattern. One approach we can try is something like:
```
MATCH (m:Measure)-[:EQUALS*0..]-(:Measure)-[d:CAPTURES]-(:Measurement)-[:EQUALS*0..]-(me)-[l:CAPTURES]-(:Measure),
scopes = (s0:Scope)-[:SCOPED]-(me), 
(:Measure)-[dd:CAPTURES]-(me)-[f:MEASURES]-(c:Constant) 

WHERE m.value = "ger"
AND all(scope in relationships(scopes) WHERE scope.storage_key IN ["scope|sc7440455|s5e237e06|saff864d3",
                                                                   "scope|sad5f9bfc|sbf396750|i102",
                                                                   "sad5f9bfc|s77153098|se8af8ab2",
                                                                   "s31098462|s77153098|s5b76a3dd"])
RETURN DISTINCT dd.storage_key, f.dimension, c.value, d.storage_key, m, f, c
```
Additionally, it looks to me like all of your relationships should be directed (`(m:Measure)-[:EQUALS*0..]->(:Measure)`), or you will get a lot of unwanted duplicate results.

**Comment by Rambatino** [comment] 2021-03-09 10:30
So those queries are derived from dynamic inputs. What's the benefit of binding the variables? 

The undirected paths are problematic, and I'll fix them now (and the MATCH queries should be using them too so I'll fix that in my code now). So thank-you for spotting that!

The code you posted actually still doesn't work as it's not necessarily _all_ of the scopes, and it's not _any_ of the scopes, either. It's that the SCOPED nodes around the Measurement must contain that set of storage keys. It's why it was constructed in this slightly obtuse way in the original query. So to reformat the original query:

``` js
              AND s0.storage_key IN ["a"] 
              AND s1.storage_key IN ["b", "e", "f"] 
              AND s2.storage_key IN ["c"] 
              AND s3.storage_key IN ["d"] 
```
i.e. the Measurement node must have a set of Scopes connected to it, such that:

* there are _at least_ four Scopes (there can be _n_ Scopes connected to any measurement)
* a successful Measurement match would have a set of Scope nodes  that contain keys:  
            * (s0:Scope {storage_key: 'a'}) AND **(s1:Scope {storage_key: 'b'})** AND (s2:Scope {storage_key: 'c'}) AND (s3:Scope {storage_key: 'd'}) 
            OR 
            * (s0:Scope {storage_key: 'a'}) AND **(s1:Scope {storage_key: 'e'})** AND (s2:Scope {storage_key: 'c'}) AND (s3:Scope {storage_key: 'd'})
            OR
            * (s0:Scope {storage_key: 'a'}) AND **(s1:Scope {storage_key: 'f'})** AND (s2:Scope {storage_key: 'c'}) AND (s3:Scope {storage_key: 'd'})

Hence I can't just flatten all the arrays together. 

It may be that there isn't an efficient query for finding Measurements that match this criteria. 🤔

I guess a kind of answer would be something like:

``` js
WHERE m.value = "ger" AND ( 
                  count([scope IN relationships(scopes) WHERE scope.storage_key IN ['a', 'b', 'c', 'd']) = 4 OR 
                  count([scope IN relationships(scopes) WHERE scope.storage_key IN ['a', 'e', 'c', 'd']) = 4 OR
                  count([scope IN relationships(scopes) WHERE scope.storage_key IN ['a', 'f', 'c', 'd']) = 4
)
```

I'll have a play around and get that to work, but if you've got any more suggestions, they would be very much appreciated!

**Comment by Rambatino** [comment] 2021-03-09 10:58
So there may be another issue here as well. With your example:

``` js
MATCH (m:Measure)-[:EQUALS*0..]-(:Measure)-[d:CAPTURES]-(:Measurement)-[:EQUALS*0..]-(me)-[l:CAPTURES]-(:Measure),
scopes = (s0:Scope)-[:SCOPED]-(me), 
(:Measure)-[dd:CAPTURES]-(me)-[f:MEASURES]-(c:Constant) 

WHERE m.value = "ger"
AND all(scope in relationships(scopes) WHERE scope.storage_key IN ["scope|sc7440455|s5e237e06|saff864d3",
                                                                   "scope|sad5f9bfc|sbf396750|i102",
                                                                   "sad5f9bfc|s77153098|se8af8ab2",
                                                                   "s31098462|s77153098|s5b76a3dd"])
RETURN DISTINCT dd.storage_key, f.dimension, c.value, d.storage_key, m, f, c
```

If I remove:

```js
AND all(scope in relationships(scopes) WHERE scope.storage_key IN ["scope|sc7440455|s5e237e06|saff864d3",
                                                                   "scope|sad5f9bfc|sbf396750|i102",
                                                                   "sad5f9bfc|s77153098|se8af8ab2",
                                                                   "s31098462|s77153098|s5b76a3dd"])
```

It obviously works, as it's just matching the Measure. However, I would have also expected this to work:


``` js
MATCH (m:Measure)-[:EQUALS*0..]-(:Measure)-[d:CAPTURES]-(:Measurement)-[:EQUALS*0..]-(me)-[l:CAPTURES]-(:Measure),
scopes = (s0:Scope)-[:SCOPED]-(me), 
(:Measure)-[dd:CAPTURES]-(me)-[f:MEASURES]-(c:Constant) 

WHERE m.value = "ger"
AND any(scope in relationships(scopes) WHERE scope.storage_key IN ["scope|sc7440455|s5e237e06|saff864d3",
                                                                   "scope|sad5f9bfc|sbf396750|i102",
                                                                   "sad5f9bfc|s77153098|se8af8ab2",
                                                                   "s31098462|s77153098|s5b76a3dd"])
RETURN DISTINCT dd.storage_key, f.dimension, c.value, d.storage_key, m, f, c
```

I've swapped the `all()` to an `any()` and yet it doesn't match anything 🤔

**Comment by swilly22** [comment] 2021-05-03 10:17
Hi @Rambatino, I would like to follow up on this issue, what's the current status?

**Comment by jeffreylovitz** [comment] 2021-11-10 16:11
On the latest version of RedisGraph, I'm unable to reproduce the issues described here.

I believe that the underlying problems have been solved, and am closing this ticket. @Rambatino if you think there are still errors here, feel free to reopen or make a new ticket!

**Closed by jeffreylovitz** 2021-11-10 16:11 UTC
