### ISSUE TITLE
Unexpected ERROR:"Unable to resolve filtered alias '()-[]-()'"

### ISSUE THREAD

**Issue by ljhhuxiaoba** [RedisGraph/RedisGraph#3013] opened 2023-03-31 14:48 UTC
I execute a query on my RedisGraph and it is supposed to output 4 as result,but an error occurred.

Redis version:6.2.10
RedisGraph version: v2.10.9
operating system: windows 10
API：Cypher version 9
query: match () match() where exists(()-[]-()) return count(*)
error message:Unable to resolve filtered alias '()-[]-()'
issue description:the query is executed on a graph containing at least one relationship,and the result should be the number of nodes squared.But when the graph contains 2 nodes,there is an error.

My graphdata:
create ({id:0})-[:T2]->(:L3)

Looking forward to your reply!

**Comment by LiorKogan** [comment] 2023-03-31 15:46
Duplicate of #2556

**Closed by LiorKogan** 2023-03-31 15:46 UTC
