### ISSUE TITLE
Optimize-label-scan mistreating OPTIONAL MATCH leading to crash

### ISSUE THREAD

**Issue by raz-mon** [RedisGraph/RedisGraph#2784] opened 2022-12-26 11:04 UTC
RedisGraph crashes after the following queries:

`CREATE (n:N)`

`MATCH (n:N) OPTIONAL MATCH (n:M)`

as a result of not treating the OPTIONAL MATCH in optimize-label-scan appropriately (need to neglect it).

**Comment by LiorKogan** [comment] 2022-12-26 11:07
Duplicate of #2631

**Comment by LiorKogan** [comment] 2022-12-26 11:07
See also #2631

**Comment by LiorKogan** [comment] 2022-12-26 11:13
Duplicate of #2631

**Closed** 2022-12-26 11:12 UTC
Labels: bug
