### ISSUE TITLE
Wrong Cartesian product in OPTIONAL MATCH

### ISSUE THREAD

**Issue by ddaa2000** [RedisGraph/RedisGraph#2489] opened 2022-07-22 07:19 UTC
RedisGraph 2.8.15

After using following statements to create two nodes:
CREATE (n1)
CREATE (n2)

Then execute the following query:
MATCH (n1), (n2) OPTIONAL MATCH (n1), (n3) RETURN 0

I got 4 lines of result. However, in neo4j I got 8. And I think 2 x 2 x 2 should be the right answer. Is this a bug or it is caused by the different cypher standard betwen these two databases ?

**Comment by LiorKogan** [comment] 2022-07-22 14:35
Duplicate of #2205 

Neo4j:

```
CREATE (n1)
CREATE (n2)
MATCH (n1), (n2) OPTIONAL MATCH (n1), (n3) RETURN [id(n1),id(n2),id(n3)]
```
[0,0,0]
[0,1,0]
[0,0,1]
[0,1,1]
[1,0,0]
[1,1,0]
[1,0,1]
[1,1,1]

RedisGraph:

```
GRAPH.DELETE g
GRAPH.QUERY g "CREATE (n1)"
GRAPH.QUERY g "CREATE (n2)"
GRAPH.QUERY g "MATCH (n1), (n2) OPTIONAL MATCH (n1), (n3) RETURN [id(n1),id(n2),id(n3)]"
```
[0, 0, 0]
[1, 0, 0]
[0, 1, 0]
[1, 1, 0]

**Closed by LiorKogan** 2022-07-22 14:35 UTC
