### ISSUE TITLE
need command to list all indices

### ISSUE THREAD

**Issue by renewooller** [RedisGraph/RedisGraph#830] opened 2019-12-19 21:38 UTC
Need a command like `:schema` to list all the indices

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/redisgraph/x5FYj-ufzuQ

**Comment by gkorland** [comment] 2020-11-25 15:58
ref #905

**Comment by swilly22** [comment] 2020-11-25 18:47
Closing as this is a duplicate of #905

**Closed by swilly22** 2020-11-25 18:47 UTC
