### ISSUE TITLE
Mixed aggregate and non-aggregate values within a map cause incorrect results

### ISSUE THREAD

**Issue by jeffreylovitz** [RedisGraph/RedisGraph#1669] opened 2021-04-21 18:11 UTC
Given the query:
```
UNWIND [1,2,3] AS agg UNWIND ['a', 'b', 'c'] AS key RETURN {sum: SUM(agg), key: key} AS map
```
We receive the incorrect result set:
```
1) 1) "map"
2) 1) 1) "{sum: 18.000000, key: NULL}"
```
Instead of the expected:
```
1) 1) "map"
2) 1) 1) "{sum: 6.000000, key: a}"
   2) 1) "{sum: 6.000000, key: b}"
   3) 1) "{sum: 6.000000, key: c}"
```
Because `OpAggregate` superficially operates on one expression (`toMap`), the key and aggregate expressions are not disambiguated properly, causing the `key` to never be evaluated and the aggregation to be performed as though there is only one group.

**Comment by OfirMos** [comment] 2021-06-22 08:44
The issue is resolved by not allowing aggregate function calls to be nested withing maps.

This is the output when trying the above query:

127.0.0.1:6379> GRAPH.QUERY g “UNWIND [1,2,3] AS agg UNWIND [‘a’, ‘b’, ‘c’] AS key RETURN {sum: SUM(agg), key: key} AS map”
(error) RedisGraph does not allow aggregate function calls to be nested within maps. Aggregate functions should instead be called in a preceding WITH clause and have their aliased values referenced in the map.

**Closed** 2021-06-22 08:44 UTC
Labels: bug
